on:
  push:
    branches-ignore:
      - master
      - main

name: preview pagedown

jobs:
  build:
    runs-on: ubuntu-latest
    container: inseefrlab/utilitr:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          Rscript -e "install.packages(c('remotes','rmarkdown','bookdown'))"
          Rscript -e "remotes::install_github('rstudio/pagedown')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Render Book
        run: |
          Rscript -e 'pagedown::chrome_print(bookdown::render_book("index.Rmd", output_format = "pagedown::html_paged", browser = '/usr/bin/google-chrome', extra_args = c("--disable-gpu", "--no-sandbox")))'
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationR_pagedown
          path: DocumentationR.pdf

#--site="$NETLIFY_SITE_ID" --auth="$NETLIFY_AUTH_TOKEN"